/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Leo
 */
public class frmPrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipalVIEW
     */
    public frmPrincipalVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCadastrarPacientes = new javax.swing.JButton();
        btnRelatorioPacientes = new javax.swing.JButton();
        btnCadastrarUsuarios = new javax.swing.JButton();
        btnRelatorioUsuarios = new javax.swing.JButton();
        btnRelatorioConsulta = new javax.swing.JButton();
        btnConsulta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tela Principal");

        btnCadastrarPacientes.setBackground(new java.awt.Color(0, 151, 53));
        btnCadastrarPacientes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCadastrarPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarPacientes.setText("Cadastrar Pacientes");
        btnCadastrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPacientesActionPerformed(evt);
            }
        });

        btnRelatorioPacientes.setBackground(new java.awt.Color(0, 153, 153));
        btnRelatorioPacientes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRelatorioPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorioPacientes.setText("Relatório de Pacientes");
        btnRelatorioPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPacientesActionPerformed(evt);
            }
        });

        btnCadastrarUsuarios.setBackground(new java.awt.Color(0, 51, 153));
        btnCadastrarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCadastrarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarUsuarios.setText("Cadastrar Usuários");
        btnCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuariosActionPerformed(evt);
            }
        });

        btnRelatorioUsuarios.setBackground(new java.awt.Color(102, 102, 255));
        btnRelatorioUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRelatorioUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorioUsuarios.setText("Relatório de Usuários");
        btnRelatorioUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioUsuariosActionPerformed(evt);
            }
        });

        btnRelatorioConsulta.setBackground(new java.awt.Color(153, 0, 51));
        btnRelatorioConsulta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRelatorioConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorioConsulta.setText("Relatório de Consultas ");
        btnRelatorioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioConsultaActionPerformed(evt);
            }
        });

        btnConsulta1.setBackground(new java.awt.Color(0, 102, 102));
        btnConsulta1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnConsulta1.setForeground(new java.awt.Color(255, 255, 255));
        btnConsulta1.setText("Consultas ");
        btnConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(306, 306, 306))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(btnRelatorioUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRelatorioPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRelatorioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRelatorioUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelatorioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacientesActionPerformed

        frmCadastrarPacientesVIEW objfrmcadastrarPacientesVIEW = new frmCadastrarPacientesVIEW();
        objfrmcadastrarPacientesVIEW.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnCadastrarPacientesActionPerformed

    private void btnRelatorioPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPacientesActionPerformed

        frmRelatorioPacienteVIEW objfrmrelatorioPacienteVIEW = new frmRelatorioPacienteVIEW();
        objfrmrelatorioPacienteVIEW.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRelatorioPacientesActionPerformed

    private void btnCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuariosActionPerformed

        frmControledeAcessoView objfrmcontroleView = new frmControledeAcessoView();
        objfrmcontroleView.setVisible(true);
        dispose();    }//GEN-LAST:event_btnCadastrarUsuariosActionPerformed

    private void btnRelatorioUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioUsuariosActionPerformed
        frmRelatorioUsuarioView objfrmrelatorioUsuarioVIEW = new frmRelatorioUsuarioView();
        objfrmrelatorioUsuarioVIEW.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRelatorioUsuariosActionPerformed

    private void btnRelatorioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioConsultaActionPerformed
        frmRelatorioConsultasView objfrmrelatorioConsultasView = new frmRelatorioConsultasView();
        objfrmrelatorioConsultasView.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRelatorioConsultaActionPerformed

    private void btnConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta1ActionPerformed
        frmConsultasView objfrmconsultaView = new frmConsultasView();
        objfrmconsultaView.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnConsulta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarPacientes;
    private javax.swing.JButton btnCadastrarUsuarios;
    private javax.swing.JButton btnConsulta1;
    private javax.swing.JButton btnRelatorioConsulta;
    private javax.swing.JButton btnRelatorioPacientes;
    private javax.swing.JButton btnRelatorioUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
